using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.SceneManagement;

public class DujeonPlayerColliderHandle : MonoBehaviour
{
    private Data data;

    private AudioManager audioManager;
    private BGMManager bgmManager;

    void Awake()
    {
        data = DataManager.Instance.data;
        audioManager = FindObjectOfType<AudioManager>();
        bgmManager = FindObjectOfType<BGMManager>();
    }

    private void OnTriggerEnter(Collider other)
    {
        //---천쮔졿쎀 쥁왴챹 웒---//
        if (other.gameObject.CompareTag("Obstacle"))
        {
            if(data.isSound)
                audioManager.Play("obstacleSound");

            Debug.Log("천쮔졿쎀 쥁왴텉 뱷");
            Destroy(other.gameObject);

            if (data.playerHP != 0f)
            {
                data.playerHP -= 0.5f;
            }
        }
        //---접쫔콼윝 쥁왴챹 웒---//
        else if (other.gameObject.CompareTag("Monster"))
        {
            Debug.Log("접쫔콼윝 쥁왴텉 뱷");
            Destroy(other.gameObject);

            data.isMonster = false;
            data.monsterSpawn[0] = true;

            bgmManager.Stop();
            audioManager.AllStop();

            SceneManager.LoadScene("FightScene");//접쫔콼윝 쥁왴텅절  쮩쌰얙 퀛퀉. 첍첂 test 쟞왤쮩
        }
        //---턎줯퉜 쥁왴챹 웒---//
        else if (other.gameObject.CompareTag("Recovery"))
        {
            if (data.isSound)
                audioManager.Play("healSound");

            Debug.Log("턎줯퉜 쥁왴텉 뱷");
            Destroy(other.gameObject);

            if(data.playerHP != 3f)
            {
                data.playerHP += 0.5f;
            }
        }
    }
}
