using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class DujeonPlayerColliderHandle : MonoBehaviour
{
    private void OnCollisionEnter2D(Collision2D other)
    {
        if (other.gameObject.CompareTag("Obstacle"))
        {
            //---천쮔졿쎀 쥁왴챹 웒---//
            Debug.Log("천쮔졿쎀 쥁왴텉 뱷");
            Destroy(other.gameObject);
        }
        else if (other.gameObject.CompareTag("Monster"))
        {
            //---접쫔콼윝 쥁왴챹 웒---//
            Debug.Log("접쫔콼윝 쥁왴텉 뱷");
            Destroy(other.gameObject);
        }/*else if (other.gameObject.CompareTag("RecoveryItem"))
        {
            //턎줯퉜 쥁왴챹 웒
        }*/
    }
}
